//! Embedded templates and assets for bundle generation.

// -- Headers --

pub const FILE_HEADER: &str = r"-- Bundled with {{NAME}} (v{{VERSION}})
-- Source File: {{INPUT}}
-- This file is automatically generated. Do not modify.";

pub const RUNTIME_HEADER: &str = r"-- Runtime Library
-- This is the pre-written shim for environment virtualization.";

pub const TREE_HEADER: &str = r"-- Instance Tree Manifest
-- This section reconstructs the original instance hierarchy.";

// -- Embedded Assets --

pub const RUNTIME_BODY: &str = include_str!("runtime.lua");

// -- Darklua Configurations --

pub const DARKLUA_DEV: &str = include_str!("darklua/dev.json");
pub const DARKLUA_DEV_COMPAT: &str = include_str!("darklua/dev-compat.json");
pub const DARKLUA_REL: &str = include_str!("darklua/rel.json");
pub const DARKLUA_REL_COMPAT: &str = include_str!("darklua/rel-compat.json");
